name: repo-sync
author: Arky Asmal
description: Sync one repository branch, with the same or another repo branch
inputs:
  TARGET_REPO_URL:
    required: true
  TARGET_REPO_BRANCH: 
    required: true
  TARGET_REPO_GITHUB_ACCESS_TOKEN:
    required: true
  BOT_NAME: 
    required: true
  BOT_EMAIL:
    required: true 
runs:
  using: 'composite'
  steps: 
    - name: Set Target Repo Env Variables
      uses: ./parseGithubUrl
      with: 
        REPO_URL: ${{inputs.TARGET_REPO_URL}}
        REPO_GITHUB_ACCESS_TOKEN: ${{inputs.TARGET_REPO_GITHUB_ACCESS_TOKEN}}
        PREFIX: 'TARGET_REPO'
    - name: Get source repository name
      shell: bash
      # run: echo "SOURCE_REPO_NAME=RepoSync" >> $GITHUB_ENV    
      run: |
        'SOURCE_REPO_NAME=${GITHUB_REPOSITORY#*/}' >> $GITHUB_ENV    
    - name: Set Source Repo Env Variables
      uses: ./parseGithubUrl
      with: 
        REPO_URL: ${{format('https://github.com/{0}/{1}.git', github.repository_owner, env.SOURCE_REPO_NAME)}}
        PREFIX: 'SOURCE_REPO'
    - name: Store Source Branch Repo Name
      shell: bash
      # run: |
      #   echo "SOURCE_REPO_BRANCH=main" >> $GITHUB_ENV
      run: |
        'SOURCE_REPO_BRANCH=${{github.ref_name}}' >> $GITHUB_ENV    
    - name: Clear all files
      shell: bash
      #we run rm since we still want it tracked on repo, but not in our local env
      run: |
        rm -rf *
    - name: Check Out to Target Repo
      uses: actions/checkout@v4
      with:
        repository: ${{env.TARGET_REPO_PATH}}
        token: ${{ inputs.TARGET_REPO_GITHUB_ACCESS_TOKEN }}    
    - name: Add Source remote
      shell: bash
      run: |
        git remote add source ${{env.SOURCE_REPO_URL}}
    - name: Add Target Remote with PAT
      continue-on-error: true
      shell: bash
      run: |
        git remote add target ${{env.TARGET_REPO_URL}}
    - name: Clone Target Repo
      shell: bash 
      run: | 
        git clone -o target ${{env.TARGET_REPO_URL}}
    - name: View remotes
      shell: bash
      run: |
        git remote -v
    - name: Get branches
      shell: bash
      run: |
        git fetch source
        git fetch target
        git branch -avv
    - name: Check if target branch exists
      shell: bash
      run: |
        "TARGET_REPO_BRANCH_EXISTS=$(if [ -n "$(git ls-remote --heads target ${{ inputs.TARGET_REPO_BRANCH }})" ]; then echo true; else echo false; fi)" >> $GITHUB_ENV
    - name: Get Default Target Branch Name
      shell: bash
      run: |
        "TARGET_REPO_DEFAULT_BRANCH_NAME=$(git symbolic-ref --short HEAD)" >> $GITHUB_ENV    
    - name: Create Target Repo Branch
      if: ${{env.TARGET_REPO_BRANCH_EXISTS}} == false
      shell: bash
      run: |
        git checkout -b ${{inputs.TARGET_REPO_BRANCH}}
        git push -u target ${{inputs.TARGET_REPO_BRANCH}}
        git fetch target
        git branch -avv
    - name:  Track Target Repo Branch
      shell: bash
      run: |
        git checkout -B ${{inputs.TARGET_REPO_BRANCH}} --track ${{format('target/{0}', inputs.TARGET_REPO_BRANCH)}}
    - name: Setup git config for target repo
      shell: bash
      run: |
        git config user.name ${{inputs.BOT_NAME}}
        git config user.email ${{inputs.BOT_EMAIL}}
    - name: Merge Branches
      shell: bash
      run: |
        git merge ${{format('source/{0}', env.SOURCE_REPO_BRANCH)}} --allow-unrelated-histories -s recursive -X theirs
    - name: Push to branch
      shell: bash
      run: |
        git push -f ${{env.TARGET_REPO_URL}} ${{inputs.TARGET_REPO_BRANCH}}
    - name: Check Out to back to Source Repo
      uses: actions/checkout@v4
      with:
        repository: ${{env.SOURCE_REPO_PATH}}
        ref: ${{env.SOURCE_REPO_BRANCH}}
    - name: Restore local files
      shell: bash
      run: |
        git fetch && git checkout ${{format('source/{0}', env.SOURCE_REPO_BRANCH)}} 