name: "Test Parser"
on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches:
      - main
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    environment: prd
    steps:
    - uses: actions/checkout@v4
    - name: "Parse Github url"
      uses: ./parseGithubUrl
      with: 
        TARGET_REPO_URL: https://github.com/aasmal97/RepoSync.git
     