name: "Test Repo Sync Existing Branch"
on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches:
      - main
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    environment: prd
    steps:
    - uses: actions/checkout@v4
    - name: Test deploy
      uses: ./
      with: 
        TARGET_REPO_URL: https://github.com/aasmal97/RepoSync.git
        TARGET_REPO_BRANCH: testing
        TARGET_REPO_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
        BOT_NAME: testing-bot
        BOT_EMAIL: arkyasmal@gmail.com
     

