name: "Test Workflow 3"
on: [push, pull_request]
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Env
      uses: ./
      with: 
        REACT_APP_SECRETS: ${{toJson(secrets)}}
        ENV_FILE_NAME: 'local'
        DESTINATION_PATH: ${{ github.workspace }}/src
    - name: List Env file
      run: cd src; ls -a


